# Generated by Django 6.0.7 on 2026-08-13 09:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_celerytasklog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True, verbose_name='Ключ')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Область корректировок',
                'verbose_name_plural': 'Области корректировок',
                'db_table': 'panel_correction_scope',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('rule', 'Правило L1'), ('object', 'Корректный объект L2')], max_length=16, verbose_name='Вид')),
                ('target_id', models.PositiveBigIntegerField(verbose_name='ID сущности')),
                ('input_fingerprint', models.CharField(max_length=64, verbose_name='Отпечаток входа')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Число применений')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Использование корректировки',
                'verbose_name_plural': 'Использования корректировок',
                'db_table': 'panel_correction_usage',
                'indexes': [models.Index(fields=['kind', 'target_id'], name='panel_cusage_kind_target_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'target_id', 'input_fingerprint'), name='panel_cusage_kind_target_fp_uniq')],
            },
        ),
        migrations.CreateModel(
            name='CorrectObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('entity_type', models.SlugField(max_length=64, verbose_name='Тип сущности')),
                ('external_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Внешний ID')),
                ('canonical_value', models.CharField(max_length=500, verbose_name='Каноническое значение')),
                ('origin', models.CharField(choices=[('imported', 'Импортирован'), ('clustered', 'Создан кластеризацией'), ('manual', 'Создан вручную')], default='manual', max_length=16, verbose_name='Происхождение')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_objects', to='panel.correctionscope', verbose_name='Область')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Корректный объект',
                'verbose_name_plural': 'Корректные объекты',
                'db_table': 'panel_correct_object',
                'ordering': ['entity_type', 'canonical_value', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DisambiguationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('entity_type', models.SlugField(max_length=64, verbose_name='Тип сущности')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Контекст')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='Отпечаток контекста')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('resolved', 'Разрешён'), ('unresolved', 'Неразрешён')], default='open', max_length=16, verbose_name='Статус')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disambiguation_cases', to='panel.correctionscope', verbose_name='Область')),
                ('selected_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_cases', to='panel.correctobject', verbose_name='Выбранный объект')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Кейс неоднозначности',
                'verbose_name_plural': 'Кейсы неоднозначности',
                'db_table': 'panel_disambiguation_case',
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DisambiguationCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Оценка [0..1]')),
                ('evidence', models.JSONField(blank=True, default=dict, verbose_name='Доказательства')),
                ('source', models.CharField(default='l2', max_length=64, verbose_name='Источник')),
                ('correct_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disambiguation_candidates', to='panel.correctobject', verbose_name='Корректный объект')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='panel.disambiguationcase', verbose_name='Кейс')),
            ],
            options={
                'verbose_name': 'Кандидат разрешения',
                'verbose_name_plural': 'Кандидаты разрешения',
                'db_table': 'panel_disambiguation_candidate',
                'ordering': ['-score', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EntityCreationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('entity_type', models.SlugField(max_length=64, verbose_name='Тип сущности')),
                ('confirmation_threshold', models.PositiveIntegerField(default=3, help_text='Минимальное число похожих несвязанных вариантов для создания объекта.', verbose_name='Порог кластера')),
                ('auto_link_threshold', models.FloatField(default=0.95, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Порог авто-связи [0..1]')),
                ('suggest_threshold', models.FloatField(default=0.8, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Порог кандидатов [0..1]')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_policies', to='panel.correctionscope', verbose_name='Область')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Политика создания сущностей',
                'verbose_name_plural': 'Политики создания сущностей',
                'db_table': 'panel_entity_creation_policy',
            },
        ),
        migrations.CreateModel(
            name='SpellingVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('entity_type', models.SlugField(max_length=64, verbose_name='Тип сущности')),
                ('value', models.CharField(max_length=500, verbose_name='Значение')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spelling_variants', to='panel.correctionscope', verbose_name='Область')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Вариант написания',
                'verbose_name_plural': 'Варианты написания',
                'db_table': 'panel_spelling_variant',
                'ordering': ['entity_type', 'value', 'id'],
            },
        ),
        migrations.AddField(
            model_name='disambiguationcase',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disambiguation_cases', to='panel.spellingvariant', verbose_name='Вариант'),
        ),
        migrations.CreateModel(
            name='TextRewriteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('mode', models.CharField(choices=[('exact', 'Точное совпадение всей строки'), ('substring', 'Подстрока'), ('re_spaces', 'Regex с упрощёнными пробелами')], default='exact', max_length=16, verbose_name='Режим')),
                ('search', models.CharField(max_length=500, verbose_name='Искать')),
                ('replacement', models.CharField(max_length=500, verbose_name='Заменить на')),
                ('preprocess', models.JSONField(blank=True, default=list, help_text='Список id трансформеров, применяемых до сопоставления.', verbose_name='Препроцессоры')),
                ('priority', models.IntegerField(default=100, help_text='Меньшее значение применяется раньше.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Приоритет')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewrite_rules', to='panel.correctionscope', verbose_name='Область')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Правило перезаписи',
                'verbose_name_plural': 'Правила перезаписи',
                'db_table': 'panel_text_rewrite_rule',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VariantObjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Утверждено'), ('forbidden', 'Запрещено')], default='pending', max_length=16, verbose_name='Статус')),
                ('source', models.CharField(choices=[('import', 'Импорт'), ('fuzzy', 'Нечёткий поиск'), ('cluster', 'Кластеризация'), ('manual', 'Вручную')], default='fuzzy', max_length=16, verbose_name='Источник')),
                ('score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Схожесть [0..1]')),
                ('confirmation_count', models.PositiveIntegerField(default=0, verbose_name='Подтверждения')),
                ('correct_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_links', to='panel.correctobject', verbose_name='Корректный объект')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_links', to='panel.spellingvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Связь варианта с объектом',
                'verbose_name_plural': 'Связи вариантов с объектами',
                'db_table': 'panel_variant_object_link',
                'ordering': ['-score', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='correctobject',
            index=models.Index(fields=['scope', 'entity_type'], name='panel_cobj_scope_type_idx'),
        ),
        migrations.AddIndex(
            model_name='correctobject',
            index=models.Index(fields=['canonical_value'], name='panel_cobj_canonical_idx'),
        ),
        migrations.AddIndex(
            model_name='correctobject',
            index=models.Index(fields=['external_id'], name='panel_cobj_external_idx'),
        ),
        migrations.AddConstraint(
            model_name='correctobject',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('scope', 'entity_type', 'external_id'), name='panel_cobj_scope_type_ext_uniq'),
        ),
        migrations.AddConstraint(
            model_name='correctobject',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', '')), fields=('scope', 'entity_type', 'canonical_value'), name='panel_cobj_scope_type_canon_uniq'),
        ),
        migrations.AddConstraint(
            model_name='disambiguationcandidate',
            constraint=models.UniqueConstraint(fields=('case', 'correct_object'), name='panel_dcand_case_object_uniq'),
        ),
        migrations.AddConstraint(
            model_name='entitycreationpolicy',
            constraint=models.UniqueConstraint(fields=('scope', 'entity_type'), name='panel_epol_scope_type_uniq'),
        ),
        migrations.AddIndex(
            model_name='spellingvariant',
            index=models.Index(fields=['scope', 'entity_type', 'value'], name='panel_svar_scope_type_val_idx'),
        ),
        migrations.AddConstraint(
            model_name='spellingvariant',
            constraint=models.UniqueConstraint(fields=('scope', 'entity_type', 'value'), name='panel_svar_scope_type_value_uniq'),
        ),
        migrations.AddIndex(
            model_name='disambiguationcase',
            index=models.Index(fields=['status'], name='panel_dcase_status_idx'),
        ),
        migrations.AddIndex(
            model_name='disambiguationcase',
            index=models.Index(fields=['scope', 'entity_type', 'status'], name='panel_dcase_scope_type_st_idx'),
        ),
        migrations.AddConstraint(
            model_name='disambiguationcase',
            constraint=models.UniqueConstraint(fields=('scope', 'variant', 'fingerprint'), name='panel_dcase_scope_var_fp_uniq'),
        ),
        migrations.AddIndex(
            model_name='textrewriterule',
            index=models.Index(fields=['scope', 'enabled', 'priority'], name='panel_rewr_scope_en_prio_idx'),
        ),
        migrations.AddIndex(
            model_name='textrewriterule',
            index=models.Index(fields=['mode', 'priority'], name='panel_rewr_mode_prio_idx'),
        ),
        migrations.AddIndex(
            model_name='variantobjectlink',
            index=models.Index(fields=['status'], name='panel_volink_status_idx'),
        ),
        migrations.AddIndex(
            model_name='variantobjectlink',
            index=models.Index(fields=['variant', 'status'], name='panel_volink_var_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='variantobjectlink',
            constraint=models.UniqueConstraint(fields=('variant', 'correct_object'), name='panel_volink_variant_object_uniq'),
        ),
    ]
