"""
Django settings for vstu_schedule project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

from vstu_schedule.utils import dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Пути для сервиса обновления расписания
TEMP_DIR = BASE_DIR / "temp"
DATA_STORAGE_DIR = BASE_DIR / "data"
if os.getenv("RUNNING_IN_DOCKER") != "1":
    load_dotenv(BASE_DIR / ".env.local")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = dotenv.get(
    "SECRET_KEY", default="django-insecure-wdt!94+_==sh4e-0849w05gz#y)93=km05)@6d84(6f4%wrnbp"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = dotenv.get_bool("DEBUG")

ALLOWED_HOSTS = dotenv.get_list("ALLOWED_HOSTS", default=["*"])
CSRF_TRUSTED_ORIGINS = dotenv.get_list("CSRF_TRUSTED_ORIGINS", default=[])

REDIS_URL = dotenv.get("REDIS_URL", "redis://redis:6379/0")
REDIS_CACHE_URL = dotenv.get("REDIS_CACHE_URL", "redis://redis:6379/1")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_beat",
    "dmr",
    "apps.common",
    "apps.api",
    "apps.panel",
    "apps.client",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "vstu_schedule.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.common.context_processors.admin_alerts",
            ],
        },
    },
]

WSGI_APPLICATION = "vstu_schedule.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = dotenv.get("DB_ENGINE", "django.db.backends.postgresql")

DATABASES = {
    "default": {
        "ENGINE": DB_ENGINE,
        "NAME": dotenv.get("POSTGRES_DB"),
        "USER": dotenv.get("POSTGRES_USER"),
        "PASSWORD": dotenv.get("POSTGRES_PASSWORD"),
        "HOST": dotenv.get("DB_HOST", "db"),
        "PORT": dotenv.get("DB_PORT", 5432),
        "OPTIONS": (
            {
                "pool": not DEBUG,
                "connect_timeout": 10,
            }
            if DB_ENGINE != "django.db.backends.sqlite3"
            else {}
        ),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ru"
LANGUAGES = [
    ("ru", "Русский"),
    ("en", "English"),
]
TIME_ZONE = "Europe/Volgograd"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_DIRS = [
    BASE_DIR / "apps" / "client" / "static",
]
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Timetable and client limits
CLIENT_FILTER_OPTIONS_CACHE_KEY = "client:schedule:filter-options:v1"
CLIENT_FILTER_OPTIONS_CACHE_TIMEOUT_SECONDS = 2 * 60 * 60
CLIENT_MAX_FILTERED_EVENTS = 350
TIMETABLE_FILE_DOWNLOAD_TIMEOUT_SECONDS = 30
TIMETABLE_MAX_DOWNLOAD_BYTES = 2 * 1024 * 1024
TIMETABLE_WEB_REQUEST_TIMEOUT_SECONDS = 10

# API settings
API_ACCESS_TOKEN_SECONDS = 15 * 60
API_EXPORT_ANONYMOUS_RATE_LIMIT = 30
API_EXPORT_ANONYMOUS_RATE_WINDOW_SECONDS = 60
API_TOKEN_RATE_LIMIT = 10
API_TOKEN_RATE_WINDOW_SECONDS = 60
API_MODEL_LIST_LIMIT = 500

# Celery Beat Config
DISABLE_CELERY = dotenv.get_bool("DISABLE_CELERY", default=False)

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
    }
}

if DISABLE_CELERY:
    # --- Режим БЕЗ Celery (Синхронный) ---
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True  # Ошибки задач будут вылетать прямо в консоль Django
    CELERY_BROKER_URL = "memory://"  # Используем память вместо Redis
    CELERY_RESULT_BACKEND = "cache+memory://"
else:
    # --- Режим С Celery (Фоновый) ---
    CELERY_TASK_ALWAYS_EAGER = False
    # Используем ваши значения или дефолты
    CELERY_BROKER_URL = dotenv.get("CELERY_BROKER_URL", "redis://redis:6379/0")
    CELERY_RESULT_BACKEND = dotenv.get("CELERY_RESULT_BACKEND", "redis://redis:6379/0")

# Общие настройки Celery
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_TASK_TRACK_STARTED = True
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# Logging
LOGS_DIR = BASE_DIR / "logs"
service_name = dotenv.get("SERVICE_NAME", "django")
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,  # Не отключаем стандартные логгеры Django
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {module}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOGS_DIR / f"{service_name}.log",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,  # Хранить 5 последних файлов
            "formatter": "verbose",
        },
        "task_db": {
            "class": "apps.panel.services.task_logging.CeleryTaskLogHandler",
            "level": "INFO",
        },
    },
    "loggers": {
        # Ваш основной логгер для приложений
        "apps": {
            "handlers": ["console", "file", "task_db"],
            "level": "INFO",
            "propagate": True,
        },
        "vstu_schedule": {
            "handlers": ["console", "file", "task_db"],
            "level": "INFO",
            "propagate": True,
        },
        # Логгер для самого Django (уменьшаем шум)
        "django": {
            "handlers": ["console", "file"],
            "level": "WARNING",  # Пишем только ошибки и предупреждения
            "propagate": False,
        },
        # Логгер для Celery
        "celery": {
            "handlers": ["console", "file", "task_db"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

LOGIN_URL = "/panel/login/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Import entity corrections (L1/L2/L3). Explicit pipeline args override these.
IMPORT_USE_CORRECTIONS = dotenv.get_bool("IMPORT_USE_CORRECTIONS", default=False)
IMPORT_CORRECTIONS_STRICT = dotenv.get_bool("IMPORT_CORRECTIONS_STRICT", default=False)
